# Generated by Django 4.1.5 on 2023-01-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='conten',
            new_name='content',
        ),
    ]
